export const GET_STOCK_DATA_REQUEST = 'GET_STOCK_DATA_REQUEST';
export const GET_STOCK_DATA_SUCCESS = 'GET_STOCK_DATA_SUCCESS';
export const INCREMENT = 'INCREMENT';
export const USERS_ERROR = 'USERS_ERROR';


